import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link, useLocation } from 'react-router-dom';
import { FaLaughWink, FaCog, FaTable, FaUser, FaBuilding, FaUsers, FaSignOutAlt } from 'react-icons/fa';
import { useAuth } from '../context/AuthContext';
const Sidebar = () => {
    const location = useLocation();
    const { user, logout } = useAuth();
    const isActive = (path) => location.pathname === path;
    return (_jsxs("ul", { className: "navbar-nav bg-gradient-primary sidebar sidebar-dark accordion", id: "accordionSidebar", children: [_jsx(Link, { className: "sidebar-brand d-flex align-items-center justify-content-center", to: "/", children: _jsx("div", { className: "sidebar-brand-icon rotate-n-15", children: _jsx(FaLaughWink, { size: 32 }) }) }), _jsx("hr", { className: "sidebar-divider my-0" }), _jsx("hr", { className: "sidebar-divider" }), _jsx("div", { className: "sidebar-heading", children: "Interface" }), _jsx("li", { className: `nav-item ${isActive('/contacts') ? 'active' : ''}`, children: _jsxs(Link, { className: "nav-link", to: "/contacts", children: [_jsx(FaTable, { className: "me-2" }), _jsx("span", { children: "Contacts" })] }) }), _jsx("li", { className: `nav-item ${isActive('/admin/companies') ? 'active' : ''}`, children: _jsxs(Link, { className: "nav-link", to: "/admin/companies", children: [_jsx(FaBuilding, { className: "me-2" }), _jsx("span", { children: "Companies" })] }) }), _jsx("li", { className: `nav-item ${isActive('/admin/users') ? 'active' : ''}`, children: _jsxs(Link, { className: "nav-link", to: "/admin/users", children: [_jsx(FaUsers, { className: "me-2" }), _jsx("span", { children: "Users" })] }) }), _jsx("li", { className: `nav-item ${isActive('/admin/visibility') ? 'active' : ''}`, children: _jsxs(Link, { className: "nav-link", to: "/admin/visibility", children: [_jsx(FaCog, { className: "me-2" }), _jsx("span", { children: "Visibility" })] }) }), _jsx("hr", { className: "sidebar-divider d-none d-md-block" }), _jsx("hr", { className: "sidebar-divider d-none d-md-block" }), _jsx("div", { className: "sidebar-heading", children: "User Profile" }), _jsx("li", { className: "nav-item", children: _jsxs("div", { className: "nav-link d-flex flex-column align-items-start", children: [_jsxs("div", { className: "d-flex align-items-center mb-2", children: [_jsx("div", { className: "rounded-circle bg-white d-flex align-items-center justify-content-center me-2", style: { width: 32, height: 32 }, children: _jsx(FaUser, { className: "text-primary" }) }), _jsxs("div", { className: "d-flex flex-column", children: [_jsx("span", { className: "text-white small font-weight-bold", title: user?.email, children: user?.email || 'Loading...' }), _jsx("span", { className: "text-white-50 x-small", style: { fontSize: '0.75rem' }, children: user?.role || 'Guest' })] })] }), _jsxs("button", { className: "btn btn-danger btn-sm w-100 d-flex align-items-center justify-content-center", onClick: (e) => {
                                e.preventDefault();
                                logout();
                                window.location.href = '/login';
                            }, children: [_jsx(FaSignOutAlt, { className: "me-2" }), "Logout"] })] }) })] }));
};
export default Sidebar;
